# Generated by Django 4.0 on 2022-07-20 20:37

import computed_property.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='Nombre Producto')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='PVP')),
                ('recargo_interior', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Recargo Interior')),
                ('porcentaje_vv', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='% Vendedor')),
                ('images', models.ImageField(blank=True, upload_to='photos/products', verbose_name='Imagen')),
                ('stock', computed_property.fields.ComputedIntegerField(blank=True, compute_from='stock_total', editable=False, null=True, verbose_name='Stock')),
                ('is_available', models.BooleanField(blank=True, default=True, null=True, verbose_name='Disponible')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['product_name', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name='Subtitulo')),
                ('variation_category', models.CharField(choices=[('Edicion', 'Edicion')], default='Edicion', max_length=200, verbose_name='Variacion')),
                ('variation_value', models.CharField(max_length=200, verbose_name='Edicion')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/products', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Edicion',
                'verbose_name_plural': 'Ediciones',
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'verbose_name': 'Valoracion',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['rating'],
            },
        ),
        migrations.AddConstraint(
            model_name='variation',
            constraint=models.UniqueConstraint(fields=('product', 'variation_value'), name='id_titulo_edicion'),
        ),
    ]
