# Generated by Django 4.0 on 2022-07-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_banner_alter_variation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='precio_ed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Precio Ed.'),
        ),
    ]
