# Generated by Django 3.2.14 on 2022-08-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220804_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('Clarin', 'Clarin'), ('La Nacion', 'La Nacion'), ('Planeta', 'Planeta'), ('Salvat', 'Salvat'), ('Perfil', 'Perfil'), ('Otro', 'Otro')], max_length=100, null=True, verbose_name='Proveedor'),
        ),
    ]
