# Generated by Django 4.0 on 2022-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Pedido'),
        ),
    ]
