# Generated by Django 4.0 on 2022-07-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderproduct_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=60, verbose_name='Numero de Pedido'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Numero de Pedido'),
        ),
    ]
